services:
  proxy:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./zero_trust.db:/code/zero_trust.db
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
